
export const villas = [
  {
    id: 1,
    name: "Villa Luna",
    location: "Monaco",
    category: "Mountains",
    guests: 11,
    bedrooms: 6,
    bathrooms: 10,
    squareMeter: "400",
    rating: 4.7,
    image: "/villa1.jpg",
    dailyRent: "2499",
  },
  {
    id: 2,
    name: "Villa Tosco",
    location: "Italy",
    category: "Mountains",
    guests: 8,
    bedrooms: 8,
    bathrooms: 12,
    squareMeter: "450",
    rating: 4.4,
    image: "/villa2.jpg",
    dailyRent: "3999",
  },
  {
    id: 3,
    name: "Aphrodite",
    location: "Greece",
    category: "Seaside",
    guests: 12,
    bedrooms: 6,
    bathrooms: 6,
    squareMeter: "500",
    rating: 4.9,
    image: "/villa3.jpg",
    dailyRent: "2099",
  },
  {
    id: 4,
    name: "Villa Makarska",
    location: "Italy",
    category: "Mountains",
    guests: 12,
    bedrooms: 15,
    bathrooms: 20,
    squareMeter: "750",
    rating: 5.0,
    image: "/villa4.jpg",
    dailyRent: "2690",
  },
  {
    id: 5,
    name: "Villa Boxane",
    location: "Brazil",
    category: "Mountains",
    guests: 4,
    bedrooms: 5,
    bathrooms: 6,
    squareMeter: "275",
    rating: 4.0,
    image: "/villa5.jpg",
    dailyRent: "2000",
  },
  {
    id: 6,
    name: "Aphrodite",
    location: "Paris",
    category: "Seaside",
    guests: 12,
    bedrooms: 6,
    bathrooms: 6,
    squareMeter: "500",
    rating: 4.9,
    image: "/villa6.jpg",
    dailyRent: "3220",
  },
  {
    id: 7,
    name: "Villa Sunset",
    location: "Italy",
    category: "Mountains",
    guests: 15,
    bedrooms: 8,
    bathrooms: 10,
    squareMeter: "1000",
    rating: 4.8,
    image: "/villa7.jpg",
    dailyRent: "2800",
  },
  {
    id: 8,
    name: "White Lady",
    location: "Korea",
    category: "Seaside",
    guests: 25,
    bedrooms: 25,
    bathrooms: 25,
    squareMeter: "1500",
    rating: 5.0,
    image: "/villa8.jpg",
    dailyRent: "4000",
  },
  {
    id: 9,
    name: "Thebes",
    location: "china",
    category: "Seaside",
    guests: 5,
    bedrooms: 6,
    bathrooms: 6,
    squareMeter: "240",
    rating: 3.8,
    image: "/villa9.jpg",
    dailyRent: "1290",
  }, {
    id: 10,
    name: "jismar",
    location: "Paris",
    category: "Seaside",
    guests: 2,
    bedrooms: 2,
    bathrooms: 1,
    squareMeter: "140",
    rating: 3,
    image: "/villa10.jpg",
    dailyRent: "2200",
  },
  {
    id: 11,
    name: "Balnca",
    location: "Japan",
    category: "Mountain",
    guests: 4,
    bedrooms: 5,
    bathrooms: 4,
    squareMeter: "340",
    rating: 4,
    image: "/villa11.jpg",
    dailyRent: "7790",
  },
  {
    id: 12,
    name: "adidbaa",
    location: "France",
    category: "Seaside",
    guests: 2,
    bedrooms: 6,
    bathrooms:3,
    squareMeter: "440",
    rating: 2,
    image: "/villa12.jpg",
    dailyRent: "6699",
  },{
    id: 13,
    name: "nikka",
    location: "Russia",
    category: "Mountain",
    guests: 2,
    bedrooms: 4,
    bathrooms: 2,
    squareMeter: "440",
    rating: 5,
    image: "/villa13.jpg",
    dailyRent: "2299",
  },{
    id: 14,
    name: "Exmaba",
    location: "india",
    category: "Seaside",
    guests: 2,
    bedrooms: 4,
    bathrooms: 2,
    squareMeter: "440",
    rating: 5,
    image: "/villa14.jpg",
    dailyRent: "1119",
  },{
    id: 15,
    name: "Samba",
    location: "Russia",
    category: "Mountain",
    guests: 2,
    bedrooms: 4,
    bathrooms: 2,
    squareMeter: "440",
    rating: 4,
    image: "/villa15.jpg",
    dailyRent: "2222",
  },{
    id: 16,
    name: " Bisthar",
    location: "Croatia",
    category: "Seaside",
    guests: 2,
    bedrooms: 4,
    bathrooms: 2,
    squareMeter: "440",
    rating: 5,
    image: "/villa16.jpg",
    dailyRent: "8999",
  },{
    id: 17,
    name: "Bruthh",
    location: "Brazil",
    category: "Mountain",
    guests: 2,
    bedrooms: 4,
    bathrooms: 2,
    squareMeter: "440",
    rating: 5,
    image: "/villa17.jpg",
    dailyRent: "999",
  },{
    id: 18,
    name: "Stayy",
    location: "Brazil",
    category: "Seaside",
    guests: 2,
    bedrooms: 4,
    bathrooms: 2,
    squareMeter: "440",
    rating: 5,
    image: "/villa18.jpg",
    dailyRent: "2229",
  },
];

